#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

matrix:
  include:
    - os: linux
      r: release
      r_packages:
      - xml2
      - covr
      after_success:
      - Rscript -e 'library(covr); codecov()'
      env: NB='w/ covr' ## Just a label
    - os: linux
      r: devel
    - os: osx
      r: release

bioc_packages:
  - snpStats
  - HiTC

notifications:
  email:
    on_success: change
    on_failure: change
