library("adjclust")
library("snpStats")

context("Comparison of the results of snpclust function in latest version of adjclust package with results generated by adjClustBand_heap in primitive version of adjclust package")

test_that("snpclust function gives results identical to results of adjClustBand_heap in primitive version of adjclust stored in prevfit.rda", {

  data("prevfit", package="adjclust")
  
  data("ld.example", package="snpStats")
  p <- ncol(ceph.1mb)
  nSamples <- nrow(ceph.1mb)
  h <- 100
  ceph.1mb[4,286]@.Data[1,1] <- as.raw(3) ## to avoid NaNs
  ld.ceph <- ld(ceph.1mb, stats="R.squared", depth=h)
  ld.ceph <- round(ld.ceph, digits=10)
  
  #case1: Input belongs to class Matrix::dgCMatrix generated by snpStats::ld function
  fit1 <- snpclust(ld.ceph, 100)
  expect_equal(fit1$merge, prevfit$merge)
  expect_equal(fit1$height, prevfit$height)
    
  #case2: Input belongs to class snpStats::SnpMatrix
  fit2 <- snpclust(ceph.1mb, 100, "R.squared")  
  expect_equal(fit2$merge, prevfit$merge)
  expect_equal(fit2$height, prevfit$height)  
  
  #case3:Input belongs class base::matrix
  ceph.1mb <- as.matrix(ceph.1mb)
  fit3 <- snpclust(ceph.1mb, 100, "R.squared")  
  expect_equal(fit3$merge, prevfit$merge)
  expect_equal(fit3$height, prevfit$height)  
  
})
