library("adjclust")
library("snpStats")

context("Ascending compatibility of the adjclust algorithm")

test_that("snpClust gives results identical to those of adjclust 0.3.0", {
    
    ## Note: this test depends on external data (genotypes) and functions 
    ## (snpStats::ld) which may change over time
    skip_on_cran() 
    
    data("res_adjclust_0.3.0", package = "adjclust")
    prevfit <- res_adjclust_0.3.0
    
    #Input data: Matrix::dgCMatrix generated by snpStats::ld
    data("ld.ceph", package = "adjclust")
    fit <- snpClust(ld.ceph, h = 100)
    expect_equal(fit$merge, prevfit$merge)
    expect_equal(fit$height, prevfit$height, tolerance=1e-5)
})
