// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// HeapHop2
Rcpp::NumericVector HeapHop2(Rcpp::NumericVector Input, const int p, const int h, const int NbCLasses);
RcppExport SEXP adjclust_HeapHop2(SEXP InputSEXP, SEXP pSEXP, SEXP hSEXP, SEXP NbCLassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Input(InputSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type NbCLasses(NbCLassesSEXP);
    __result = Rcpp::wrap(HeapHop2(Input, p, h, NbCLasses));
    return __result;
END_RCPP
}
// HeapHop
Rcpp::NumericVector HeapHop(Rcpp::NumericVector Input, const int p, const int h, const int NbCLasses);
RcppExport SEXP adjclust_HeapHop(SEXP InputSEXP, SEXP pSEXP, SEXP hSEXP, SEXP NbCLassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Input(InputSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type NbCLasses(NbCLassesSEXP);
    __result = Rcpp::wrap(HeapHop(Input, p, h, NbCLasses));
    return __result;
END_RCPP
}
