// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// HeapHop2
Rcpp::NumericVector HeapHop2(Rcpp::NumericVector Input, const int p, const int h, const int NbCLasses);
RcppExport SEXP _adjclust_HeapHop2(SEXP InputSEXP, SEXP pSEXP, SEXP hSEXP, SEXP NbCLassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Input(InputSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type NbCLasses(NbCLassesSEXP);
    rcpp_result_gen = Rcpp::wrap(HeapHop2(Input, p, h, NbCLasses));
    return rcpp_result_gen;
END_RCPP
}
// HeapHop
Rcpp::NumericVector HeapHop(Rcpp::NumericVector Input, const int p, const int h, const int NbCLasses);
RcppExport SEXP _adjclust_HeapHop(SEXP InputSEXP, SEXP pSEXP, SEXP hSEXP, SEXP NbCLassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Input(InputSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type NbCLasses(NbCLassesSEXP);
    rcpp_result_gen = Rcpp::wrap(HeapHop(Input, p, h, NbCLasses));
    return rcpp_result_gen;
END_RCPP
}
