# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HeapHop2 <- function(Input, p, h, NbCLasses) {
    .Call('adjclust_HeapHop2', PACKAGE = 'adjclust', Input, p, h, NbCLasses)
}

HeapHop <- function(Input, p, h, NbCLasses) {
    .Call('adjclust_HeapHop', PACKAGE = 'adjclust', Input, p, h, NbCLasses)
}

