# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matL_sparse <- function(Csq, h) {
    .Call(`_adjclust_matL_sparse`, Csq, h)
}

matL_full <- function(Csq, h) {
    .Call(`_adjclust_matL_full`, Csq, h)
}

matL_sparse_rowCumsums <- function(Csq, h, nthreads) {
    .Call(`_adjclust_matL_sparse_rowCumsums`, Csq, h, nthreads)
}

matL_full_rowCumsums <- function(Csq, h, nthreads) {
    .Call(`_adjclust_matL_full_rowCumsums`, Csq, h, nthreads)
}

matR_sparse <- function(Csq, h) {
    .Call(`_adjclust_matR_sparse`, Csq, h)
}

matR_full <- function(Csq, h) {
    .Call(`_adjclust_matR_full`, Csq, h)
}

matR_sparse_rowCumsums <- function(Csq, h, nthreads) {
    .Call(`_adjclust_matR_sparse_rowCumsums`, Csq, h, nthreads)
}

matR_full_rowCumsums <- function(Csq, h, nthreads) {
    .Call(`_adjclust_matR_full_rowCumsums`, Csq, h, nthreads)
}

