#' Similarity matrix used in proving equivalence of full band adjclust and rioja
#'
#' A 150 X 150 similarity symmetric numeric matrix without missing values.
#'
#' @format A sparse matrix of class base::matrix.
#'
#' @source This matrix is generated by scaling the matrix provided in medium tests.
#'
"simmatrix"
